# Generated by Django 3.2.9 on 2021-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211102_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserapp',
            name='USERNAME_FIELD',
        ),
        migrations.AlterField(
            model_name='customuserapp',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
